/**
 * \file IfxQspi_regdef.h
 * \brief
 * \copyright Copyright (c) 2020 Infineon Technologies AG. All rights reserved.
 * Version: TC38XA_UM_V1.5.0.R0
 * Specification: TC3xx User Manual V1.5.0
 * MAY BE CHANGED BY USER [yes/no]: No
 *                                 IMPORTANT NOTICE
 * Use of this file is subject to the terms of use agreed between (i) you or 
 * the company in which ordinary course of business you are acting and (ii) 
 * Infineon Technologies AG or its licensees. If and as long as no such 
 * terms of use are agreed, use of this file is subject to following:


 * Boost Software License - Version 1.0 - August 17th, 2003

 * Permission is hereby granted, free of charge, to any person or 
 * organization obtaining a copy of the software and accompanying 
 * documentation covered by this license (the "Software") to use, reproduce,
 * display, distribute, execute, and transmit the Software, and to prepare
 * derivative works of the Software, and to permit third-parties to whom the 
 * Software is furnished to do so, all subject to the following:

 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.

 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE 
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 * \defgroup IfxSfr_Qspi_Registers Qspi Registers
 * \ingroup IfxSfr
 * 
 * \defgroup IfxSfr_Qspi_Registers_Bitfields Bitfields
 * \ingroup IfxSfr_Qspi_Registers
 * 
 * \defgroup IfxSfr_Qspi_Registers_union Register unions
 * \ingroup IfxSfr_Qspi_Registers
 * 
 * \defgroup IfxSfr_Qspi_Registers_struct Memory map
 * \ingroup IfxSfr_Qspi_Registers */
#ifndef IFXQSPI_REGDEF_H
#define IFXQSPI_REGDEF_H 1
/******************************************************************************/
#include "Ifx_TypesReg.h"
/******************************************************************************/

/******************************************************************************/

/******************************************************************************/


/* IfxSfr_Qspi_Registers_Bitfields */
/* Access Enable Register 0 */
typedef struct _Ifx_QSPI_ACCEN0_Bits
{
    Ifx_UReg_32Bit EN0:1;             /* [0:0] Access Enable for Master TAG ID 0 - EN0 (rw) */
    Ifx_UReg_32Bit EN1:1;             /* [1:1] Access Enable for Master TAG ID 1 - EN1 (rw) */
    Ifx_UReg_32Bit EN2:1;             /* [2:2] Access Enable for Master TAG ID 2 - EN2 (rw) */
    Ifx_UReg_32Bit EN3:1;             /* [3:3] Access Enable for Master TAG ID 3 - EN3 (rw) */
    Ifx_UReg_32Bit EN4:1;             /* [4:4] Access Enable for Master TAG ID 4 - EN4 (rw) */
    Ifx_UReg_32Bit EN5:1;             /* [5:5] Access Enable for Master TAG ID 5 - EN5 (rw) */
    Ifx_UReg_32Bit EN6:1;             /* [6:6] Access Enable for Master TAG ID 6 - EN6 (rw) */
    Ifx_UReg_32Bit EN7:1;             /* [7:7] Access Enable for Master TAG ID 7 - EN7 (rw) */
    Ifx_UReg_32Bit EN8:1;             /* [8:8] Access Enable for Master TAG ID 8 - EN8 (rw) */
    Ifx_UReg_32Bit EN9:1;             /* [9:9] Access Enable for Master TAG ID 9 - EN9 (rw) */
    Ifx_UReg_32Bit EN10:1;            /* [10:10] Access Enable for Master TAG ID 10 - EN10 (rw) */
    Ifx_UReg_32Bit EN11:1;            /* [11:11] Access Enable for Master TAG ID 11 - EN11 (rw) */
    Ifx_UReg_32Bit EN12:1;            /* [12:12] Access Enable for Master TAG ID 12 - EN12 (rw) */
    Ifx_UReg_32Bit EN13:1;            /* [13:13] Access Enable for Master TAG ID 13 - EN13 (rw) */
    Ifx_UReg_32Bit EN14:1;            /* [14:14] Access Enable for Master TAG ID 14 - EN14 (rw) */
    Ifx_UReg_32Bit EN15:1;            /* [15:15] Access Enable for Master TAG ID 15 - EN15 (rw) */
    Ifx_UReg_32Bit EN16:1;            /* [16:16] Access Enable for Master TAG ID 16 - EN16 (rw) */
    Ifx_UReg_32Bit EN17:1;            /* [17:17] Access Enable for Master TAG ID 17 - EN17 (rw) */
    Ifx_UReg_32Bit EN18:1;            /* [18:18] Access Enable for Master TAG ID 18 - EN18 (rw) */
    Ifx_UReg_32Bit EN19:1;            /* [19:19] Access Enable for Master TAG ID 19 - EN19 (rw) */
    Ifx_UReg_32Bit EN20:1;            /* [20:20] Access Enable for Master TAG ID 20 - EN20 (rw) */
    Ifx_UReg_32Bit EN21:1;            /* [21:21] Access Enable for Master TAG ID 21 - EN21 (rw) */
    Ifx_UReg_32Bit EN22:1;            /* [22:22] Access Enable for Master TAG ID 22 - EN22 (rw) */
    Ifx_UReg_32Bit EN23:1;            /* [23:23] Access Enable for Master TAG ID 23 - EN23 (rw) */
    Ifx_UReg_32Bit EN24:1;            /* [24:24] Access Enable for Master TAG ID 24 - EN24 (rw) */
    Ifx_UReg_32Bit EN25:1;            /* [25:25] Access Enable for Master TAG ID 25 - EN25 (rw) */
    Ifx_UReg_32Bit EN26:1;            /* [26:26] Access Enable for Master TAG ID 26 - EN26 (rw) */
    Ifx_UReg_32Bit EN27:1;            /* [27:27] Access Enable for Master TAG ID 27 - EN27 (rw) */
    Ifx_UReg_32Bit EN28:1;            /* [28:28] Access Enable for Master TAG ID 28 - EN28 (rw) */
    Ifx_UReg_32Bit EN29:1;            /* [29:29] Access Enable for Master TAG ID 29 - EN29 (rw) */
    Ifx_UReg_32Bit EN30:1;            /* [30:30] Access Enable for Master TAG ID 30 - EN30 (rw) */
    Ifx_UReg_32Bit EN31:1;            /* [31:31] Access Enable for Master TAG ID 31 - EN31 (rw) */
} Ifx_QSPI_ACCEN0_Bits;

/* Access Enable Register 1 */
typedef struct _Ifx_QSPI_ACCEN1_Bits
{
    Ifx_UReg_32Bit reserved_0:32;     /* [31:0] internal Reserved */
} Ifx_QSPI_ACCEN1_Bits;

/* Basic Configuration Register */
typedef struct _Ifx_QSPI_BACON_Bits
{
    Ifx_UReg_32Bit LAST:1;            /* [0:0] Last Word in a Frame - LAST (rh) */
    Ifx_UReg_32Bit IPRE:3;            /* [3:1] Prescaler for the Idle Delay - IPRE (rh) */
    Ifx_UReg_32Bit IDLE:3;            /* [6:4] Idle Delay Length - IDLE (rh) */
    Ifx_UReg_32Bit LPRE:3;            /* [9:7] Prescaler for the Leading Delay - LPRE (rh) */
    Ifx_UReg_32Bit LEAD:3;            /* [12:10] Leading Delay Length - LEAD (rh) */
    Ifx_UReg_32Bit TPRE:3;            /* [15:13] Prescaler for the Trailing Delay - TPRE (rh) */
    Ifx_UReg_32Bit TRAIL:3;           /* [18:16] Trailing Delay Length - TRAIL (rh) */
    Ifx_UReg_32Bit PARTYP:1;          /* [19:19] Parity Type - PARTYP (rh) */
    Ifx_UReg_32Bit UINT:1;            /* [20:20] User Interrupt at the PT1 Event in the Subsequent Frames - UINT (rh) */
    Ifx_UReg_32Bit MSB:1;             /* [21:21] Shift MSB or LSB First - MSB (rh) */
    Ifx_UReg_32Bit BYTE:1;            /* [22:22] Byte - BYTE (rh) */
    Ifx_UReg_32Bit DL:5;              /* [27:23] Data Length - DL (rh) */
    Ifx_UReg_32Bit CS:4;              /* [31:28] Channel Select - CS (rh) */
} Ifx_QSPI_BACON_Bits;

/* BACON_ENTRY Register */
typedef struct _Ifx_QSPI_BACONENTRY_Bits
{
    Ifx_UReg_32Bit E:32;              /* [31:0] Entry Point to the TxFIFO - E (w) */
} Ifx_QSPI_BACONENTRY_Bits;

/* Clock Control Register */
typedef struct _Ifx_QSPI_CLC_Bits
{
    Ifx_UReg_32Bit DISR:1;            /* [0:0] Module Disable Request Bit - DISR (rw) */
    Ifx_UReg_32Bit DISS:1;            /* [1:1] Module Disable Status Bit - DISS (rh) */
    Ifx_UReg_32Bit reserved_2:1;      /* [2:2] internal Reserved */
    Ifx_UReg_32Bit EDIS:1;            /* [3:3] Sleep Mode Enable Control - EDIS (rw) */
    Ifx_UReg_32Bit reserved_4:28;     /* [31:4] internal Reserved */
} Ifx_QSPI_CLC_Bits;

/* DATA_ENTRY Register ${x} */
typedef struct _Ifx_QSPI_DATAENTRY_Bits
{
    Ifx_UReg_32Bit E:32;              /* [31:0] Entry Point to the TxFIFO - E (w) */
} Ifx_QSPI_DATAENTRY_Bits;

/* Configuration Extension ${z} */
typedef struct _Ifx_QSPI_ECON_Bits
{
    Ifx_UReg_32Bit Q:6;               /* [5:0] Time Quantum - Q (rw) */
    Ifx_UReg_32Bit A:2;               /* [7:6] Bit Segment 1 - A (rw) */
    Ifx_UReg_32Bit B:2;               /* [9:8] Bit Segment 2 - B (rw) */
    Ifx_UReg_32Bit C:2;               /* [11:10] Bit Segment 3 - C (rw) */
    Ifx_UReg_32Bit CPH:1;             /* [12:12] Clock Phase - CPH (rw) */
    Ifx_UReg_32Bit CPOL:1;            /* [13:13] Clock Polarity - CPOL (rw) */
    Ifx_UReg_32Bit PAREN:1;           /* [14:14] Enable Parity Check - PAREN (rw) */
    Ifx_UReg_32Bit reserved_15:15;    /* [29:15] internal Reserved */
    Ifx_UReg_32Bit BE:2;              /* [31:30] Permutate bytes to / from Big Endian - BE (rw) */
} Ifx_QSPI_ECON_Bits;

/* Flags Clear Register */
typedef struct _Ifx_QSPI_FLAGSCLEAR_Bits
{
    Ifx_UReg_32Bit ERRORCLEARS:9;     /* [8:0] Write Only Bits for Clearing the Error Flags - ERRORCLEARS (w) */
    Ifx_UReg_32Bit TXC:1;             /* [9:9] Transmit Event Flag Clear - TXC (w) */
    Ifx_UReg_32Bit RXC:1;             /* [10:10] Receive Event Flag Clear - RXC (w) */
    Ifx_UReg_32Bit PT1C:1;            /* [11:11] PT1 Event Flag Clear - PT1C (w) */
    Ifx_UReg_32Bit PT2C:1;            /* [12:12] PT2 Event Flag Clear - PT2C (w) */
    Ifx_UReg_32Bit reserved_13:1;     /* [13:13] internal Reserved */
    Ifx_UReg_32Bit reserved_14:1;     /* [14:14] internal Reserved */
    Ifx_UReg_32Bit USRC:1;            /* [15:15] User Event Flag Clear - USRC (w) */
    Ifx_UReg_32Bit reserved_16:16;    /* [31:16] internal Reserved */
} Ifx_QSPI_FLAGSCLEAR_Bits;

/* Global Configuration Register */
typedef struct _Ifx_QSPI_GLOBALCON_Bits
{
    Ifx_UReg_32Bit TQ:8;              /* [7:0] Global Time Quantum Length - TQ (rw) */
    Ifx_UReg_32Bit reserved_8:1;      /* [8:8] internal Reserved */
    Ifx_UReg_32Bit SI:1;              /* [9:9] Status Injection - SI (rw) */
    Ifx_UReg_32Bit EXPECT:4;          /* [13:10] Time-Out Value for the Expect Phase - EXPECT (rw) */
    Ifx_UReg_32Bit LB:1;              /* [14:14] Loop-Back Control - LB (rw) */
    Ifx_UReg_32Bit DEL0:1;            /* [15:15] Delayed Mode for SLSO0 - DEL0 (rw) */
    Ifx_UReg_32Bit STROBE:5;          /* [20:16] Strobe Delay for SLSO0 in Delayed Mode - STROBE (rw) */
    Ifx_UReg_32Bit SRF:1;             /* [21:21] Stop on RxFIFO Full - SRF (rw) */
    Ifx_UReg_32Bit STIP:1;            /* [22:22] Slave Transmit Idle State Polarity - STIP (rw) */
    Ifx_UReg_32Bit reserved_23:1;     /* [23:23] internal Reserved */
    Ifx_UReg_32Bit EN:1;              /* [24:24] Enable Bit - EN (rwh) */
    Ifx_UReg_32Bit MS:2;              /* [26:25] Master Slave Mode - MS (rw) */
    Ifx_UReg_32Bit AREN:1;            /* [27:27] Automatic Reset Enable - AREN (rw) */
    Ifx_UReg_32Bit reserved_28:1;     /* [28:28] internal Reserved */
    Ifx_UReg_32Bit CLKSEL:1;          /* [29:29] Clock Select - CLKSEL (rw) */
    Ifx_UReg_32Bit RESETS:2;          /* [31:30] Bits for resetting sub-modules per software - RESETS (w) */
} Ifx_QSPI_GLOBALCON_Bits;

/* Global Configuration Register 1 */
typedef struct _Ifx_QSPI_GLOBALCON1_Bits
{
    Ifx_UReg_32Bit ERRORENS:9;        /* [8:0] Error Enable Bits - ERRORENS (rw) */
    Ifx_UReg_32Bit TXEN:1;            /* [9:9] Tx Interrupt Event Enable - TXEN (rw) */
    Ifx_UReg_32Bit RXEN:1;            /* [10:10] RX Interrupt Event Enable - RXEN (rw) */
    Ifx_UReg_32Bit PT1EN:1;           /* [11:11] Interrupt on PT1 Event Enable - PT1EN (rw) */
    Ifx_UReg_32Bit PT2EN:1;           /* [12:12] Interrupt on PT2 Event Enable - PT2EN (rw) */
    Ifx_UReg_32Bit reserved_13:1;     /* [13:13] internal Reserved */
    Ifx_UReg_32Bit reserved_14:1;     /* [14:14] internal Reserved */
    Ifx_UReg_32Bit USREN:1;           /* [15:15] Interrupt on USR Event Enable - USREN (rw) */
    Ifx_UReg_32Bit TXFIFOINT:2;       /* [17:16] Transmit FIFO Interrupt Threshold - TXFIFOINT (rw) */
    Ifx_UReg_32Bit RXFIFOINT:2;       /* [19:18] Receive FIFO Interrupt Threshold - RXFIFOINT (rw) */
    Ifx_UReg_32Bit PT1:3;             /* [22:20] Phase Transition Event 1 - PT1 (rw) */
    Ifx_UReg_32Bit PT2:3;             /* [25:23] Phase Transition Event 2 - PT2 (rw) */
    Ifx_UReg_32Bit TXFM:2;            /* [27:26] TXFIFO Mode - TXFM (rw) */
    Ifx_UReg_32Bit RXFM:2;            /* [29:28] RXFIFO Mode - RXFM (rw) */
    Ifx_UReg_32Bit reserved_30:1;     /* [30:30] internal Reserved */
    Ifx_UReg_32Bit reserved_31:1;     /* [31:31] internal Reserved */
} Ifx_QSPI_GLOBALCON1_Bits;

/* Module Identification Register */
typedef struct _Ifx_QSPI_ID_Bits
{
    Ifx_UReg_32Bit MODREV:8;          /* [7:0] Module Revision Number - MODREV (r) */
    Ifx_UReg_32Bit MODTYPE:8;         /* [15:8] Module Type - MODTYPE (r) */
    Ifx_UReg_32Bit MODNUMBER:16;      /* [31:16] Module Number Value - MODNUMBER (r) */
} Ifx_QSPI_ID_Bits;

/* Kernel Reset Register 0 */
typedef struct _Ifx_QSPI_KRST0_Bits
{
    Ifx_UReg_32Bit RST:1;             /* [0:0] Kernel Reset - RST (rwh) */
    Ifx_UReg_32Bit RSTSTAT:1;         /* [1:1] Kernel Reset Status - RSTSTAT (rh) */
    Ifx_UReg_32Bit reserved_2:30;     /* [31:2] internal Reserved */
} Ifx_QSPI_KRST0_Bits;

/* Kernel Reset Register 1 */
typedef struct _Ifx_QSPI_KRST1_Bits
{
    Ifx_UReg_32Bit RST:1;             /* [0:0] Kernel Reset - RST (rwh) */
    Ifx_UReg_32Bit reserved_1:31;     /* [31:1] internal Reserved */
} Ifx_QSPI_KRST1_Bits;

/* Kernel Reset Status Clear Register */
typedef struct _Ifx_QSPI_KRSTCLR_Bits
{
    Ifx_UReg_32Bit CLR:1;             /* [0:0] Kernel Reset Status Clear - CLR (w) */
    Ifx_UReg_32Bit reserved_1:31;     /* [31:1] internal Reserved */
} Ifx_QSPI_KRSTCLR_Bits;

/* Move Counter Register */
typedef struct _Ifx_QSPI_MC_Bits
{
    Ifx_UReg_32Bit MCOUNT:13;         /* [12:0] Move Count - MCOUNT (rw) */
    Ifx_UReg_32Bit reserved_13:3;     /* [15:13] internal Reserved */
    Ifx_UReg_32Bit CURRENT:13;        /* [28:16] Current Status of the Move Counter - CURRENT (rh) */
    Ifx_UReg_32Bit reserved_29:3;     /* [31:29] internal Reserved */
} Ifx_QSPI_MC_Bits;

/* Move Counter control Register */
typedef struct _Ifx_QSPI_MCCON_Bits
{
    Ifx_UReg_32Bit TPRE2:3;           /* [2:0] Prescaler for the Trailing Delay 2 - TPRE2 (rw) */
    Ifx_UReg_32Bit TRAIL2:3;          /* [5:3] Last Trailing Delay - TRAIL2 (rw) */
    Ifx_UReg_32Bit reserved_6:10;     /* [15:6] internal Reserved */
    Ifx_UReg_32Bit IBLEN:1;           /* [16:16] Interrupt Before Last Enable - IBLEN (rw) */
    Ifx_UReg_32Bit IBLF:1;            /* [17:17] Interrupt Before Last Flag - IBLF (rh) */
    Ifx_UReg_32Bit IBLC:1;            /* [18:18] Clear Bit for IBLF - IBLC (w) */
    Ifx_UReg_32Bit IBLS:1;            /* [19:19] Set Bit for IBLF - IBLS (w) */
    Ifx_UReg_32Bit IALEN:1;           /* [20:20] Interrupt After Last Enable - IALEN (rw) */
    Ifx_UReg_32Bit IALF:1;            /* [21:21] Interrupt After Last Flag - IALF (rh) */
    Ifx_UReg_32Bit IALC:1;            /* [22:22] Clear Bit for IALF - IALC (w) */
    Ifx_UReg_32Bit IALS:1;            /* [23:23] Set Bit for IALF - IALS (w) */
    Ifx_UReg_32Bit reserved_24:6;     /* [29:24] internal Reserved */
    Ifx_UReg_32Bit T2EN:1;            /* [30:30] TRAIL 2 Injection Enable - T2EN (rw) */
    Ifx_UReg_32Bit MCEN:1;            /* [31:31] Move Counter Enable - MCEN (rw) */
} Ifx_QSPI_MCCON_Bits;

/* MIX_ENTRY Register */
typedef struct _Ifx_QSPI_MIXENTRY_Bits
{
    Ifx_UReg_32Bit E:32;              /* [31:0] Entry Point to the TxFIFO - E (w) */
} Ifx_QSPI_MIXENTRY_Bits;

/* OCDS Control and Status */
typedef struct _Ifx_QSPI_OCS_Bits
{
    Ifx_UReg_32Bit reserved_0:4;      /* [3:0] internal Reserved */
    Ifx_UReg_32Bit reserved_4:20;     /* [23:4] internal Reserved */
    Ifx_UReg_32Bit SUS:4;             /* [27:24] OCDS Suspend Control - SUS (rw) */
    Ifx_UReg_32Bit SUS_P:1;           /* [28:28] SUS Write Protection - SUS_P (w) */
    Ifx_UReg_32Bit SUSSTA:1;          /* [29:29] Suspend State - SUSSTA (rh) */
    Ifx_UReg_32Bit reserved_30:2;     /* [31:30] internal Reserved */
} Ifx_QSPI_OCS_Bits;

/* Port Input Select Register */
typedef struct _Ifx_QSPI_PISEL_Bits
{
    Ifx_UReg_32Bit MRIS:3;            /* [2:0] Master Mode Receive Input Select (rw) */
    Ifx_UReg_32Bit reserved_3:1;      /* [3:3] internal Reserved */
    Ifx_UReg_32Bit SRIS:3;            /* [6:4] Slave Mode Receive Input Select (rw) */
    Ifx_UReg_32Bit reserved_7:1;      /* [7:7] internal Reserved */
    Ifx_UReg_32Bit SCIS:3;            /* [10:8] Slave Mode Clock Input Select (rw) */
    Ifx_UReg_32Bit reserved_11:1;     /* [11:11] internal Reserved */
    Ifx_UReg_32Bit SLSIS:3;           /* [14:12] Slave Mode Slave Select Input Selection (rw) */
    Ifx_UReg_32Bit reserved_15:17;    /* [31:15] internal Reserved */
} Ifx_QSPI_PISEL_Bits;

/* RX_EXIT Register */
typedef struct _Ifx_QSPI_RXEXIT_Bits
{
    Ifx_UReg_32Bit E:32;              /* [31:0] Read Point from the RxFIFO - E (r) */
} Ifx_QSPI_RXEXIT_Bits;

/* RX_EXIT Debug Register */
typedef struct _Ifx_QSPI_RXEXITD_Bits
{
    Ifx_UReg_32Bit E:32;              /* [31:0] Read Point from the RxFIFO - E (r) */
} Ifx_QSPI_RXEXITD_Bits;

/* Slave Select Output Control Register */
typedef struct _Ifx_QSPI_SSOC_Bits
{
    Ifx_UReg_32Bit AOL:16;            /* [15:0] Active Output Level for the SLSO Outputs - AOL (rw) */
    Ifx_UReg_32Bit OEN:16;            /* [31:16] Enable Bits for the SLSO Outputs - OEN (rw) */
} Ifx_QSPI_SSOC_Bits;

/* Status Register */
typedef struct _Ifx_QSPI_STATUS_Bits
{
    Ifx_UReg_32Bit ERRORFLAGS:9;      /* [8:0] Sticky Flags Signalling Errors - ERRORFLAGS (rwh) */
    Ifx_UReg_32Bit TXF:1;             /* [9:9] Transmit Interrupt Request Flag - TXF (rwh) */
    Ifx_UReg_32Bit RXF:1;             /* [10:10] Receive Interrupt Request Flag - RXF (rwh) */
    Ifx_UReg_32Bit PT1F:1;            /* [11:11] Phase Transition 1 Flag - PT1F (rwh) */
    Ifx_UReg_32Bit PT2F:1;            /* [12:12] Phase Transition 2 Flag - PT2F (rwh) */
    Ifx_UReg_32Bit reserved_13:1;     /* [13:13] internal Reserved */
    Ifx_UReg_32Bit reserved_14:1;     /* [14:14] internal Reserved */
    Ifx_UReg_32Bit USRF:1;            /* [15:15] User Interrupt Request Flag - USRF (rwh) */
    Ifx_UReg_32Bit TXFIFOLEVEL:3;     /* [18:16] TXFIFO Filling Level - TXFIFOLEVEL (rh) */
    Ifx_UReg_32Bit RXFIFOLEVEL:3;     /* [21:19] RXFIFO Filling Level - RXFIFOLEVEL (rh) */
    Ifx_UReg_32Bit SLAVESEL:4;        /* [25:22] Currently Active Slave Select Flag - SLAVESEL (rh) */
    Ifx_UReg_32Bit RPV:1;             /* [26:26] Received Parity Value - RPV (rh) */
    Ifx_UReg_32Bit TPV:1;             /* [27:27] Transmitted Parity Value - TPV (rh) */
    Ifx_UReg_32Bit PHASE:4;           /* [31:28] Flags the ongoing phase - PHASE (rh) */
} Ifx_QSPI_STATUS_Bits;

/* Status Register 1 */
typedef struct _Ifx_QSPI_STATUS1_Bits
{
    Ifx_UReg_32Bit BITCOUNT:8;        /* [7:0] Number of bits shifted out - BITCOUNT (r) */
    Ifx_UReg_32Bit reserved_8:20;     /* [27:8] internal Reserved */
    Ifx_UReg_32Bit BRDEN:1;           /* [28:28] Baud Rate Deviation Enable - BRDEN (rw) */
    Ifx_UReg_32Bit BRD:1;             /* [29:29] Baud Rate Deviation Flag - BRD (rwh) */
    Ifx_UReg_32Bit SPDEN:1;           /* [30:30] Spike Detection Enable - SPDEN (rw) */
    Ifx_UReg_32Bit SPD:1;             /* [31:31] Spike Detection Flag - SPD (rwh) */
} Ifx_QSPI_STATUS1_Bits;

/* Extra Large Data Configuration Register */
typedef struct _Ifx_QSPI_XXLCON_Bits
{
    Ifx_UReg_32Bit XDL:16;            /* [15:0] Extended Data Length - XDL (rw) */
    Ifx_UReg_32Bit BYTECOUNT:16;      /* [31:16] Extended Data Length - BYTECOUNT (r) */
} Ifx_QSPI_XXLCON_Bits;

/******************************************************************************/
/******************************************************************************/
/** \addtogroup IfxSfr_qspi_Registers_union
 * \{   */
/* Access Enable Register 0   */
typedef union
{
    Ifx_UReg_32Bit U;                 /* Unsigned access */
    Ifx_SReg_32Bit I;                 /* Signed access */
    Ifx_QSPI_ACCEN0_Bits B;           /* Bitfield access */
} Ifx_QSPI_ACCEN0;

/* Access Enable Register 1   */
typedef union
{
    Ifx_UReg_32Bit U;                 /* Unsigned access */
    Ifx_SReg_32Bit I;                 /* Signed access */
    Ifx_QSPI_ACCEN1_Bits B;           /* Bitfield access */
} Ifx_QSPI_ACCEN1;

/* Basic Configuration Register   */
typedef union
{
    Ifx_UReg_32Bit U;                 /* Unsigned access */
    Ifx_SReg_32Bit I;                 /* Signed access */
    Ifx_QSPI_BACON_Bits B;            /* Bitfield access */
} Ifx_QSPI_BACON;

/* BACON_ENTRY Register   */
typedef union
{
    Ifx_UReg_32Bit U;                 /* Unsigned access */
    Ifx_SReg_32Bit I;                 /* Signed access */
    Ifx_QSPI_BACONENTRY_Bits B;       /* Bitfield access */
} Ifx_QSPI_BACONENTRY;

/* Clock Control Register   */
typedef union
{
    Ifx_UReg_32Bit U;                 /* Unsigned access */
    Ifx_SReg_32Bit I;                 /* Signed access */
    Ifx_QSPI_CLC_Bits B;              /* Bitfield access */
} Ifx_QSPI_CLC;

/* DATA_ENTRY Register ${x}   */
typedef union
{
    Ifx_UReg_32Bit U;                 /* Unsigned access */
    Ifx_SReg_32Bit I;                 /* Signed access */
    Ifx_QSPI_DATAENTRY_Bits B;        /* Bitfield access */
} Ifx_QSPI_DATAENTRY;

/* Configuration Extension ${z}   */
typedef union
{
    Ifx_UReg_32Bit U;                 /* Unsigned access */
    Ifx_SReg_32Bit I;                 /* Signed access */
    Ifx_QSPI_ECON_Bits B;             /* Bitfield access */
} Ifx_QSPI_ECON;

/* Flags Clear Register   */
typedef union
{
    Ifx_UReg_32Bit U;                 /* Unsigned access */
    Ifx_SReg_32Bit I;                 /* Signed access */
    Ifx_QSPI_FLAGSCLEAR_Bits B;       /* Bitfield access */
} Ifx_QSPI_FLAGSCLEAR;

/* Global Configuration Register   */
typedef union
{
    Ifx_UReg_32Bit U;                 /* Unsigned access */
    Ifx_SReg_32Bit I;                 /* Signed access */
    Ifx_QSPI_GLOBALCON_Bits B;        /* Bitfield access */
} Ifx_QSPI_GLOBALCON;

/* Global Configuration Register 1   */
typedef union
{
    Ifx_UReg_32Bit U;                 /* Unsigned access */
    Ifx_SReg_32Bit I;                 /* Signed access */
    Ifx_QSPI_GLOBALCON1_Bits B;       /* Bitfield access */
} Ifx_QSPI_GLOBALCON1;

/* Module Identification Register   */
typedef union
{
    Ifx_UReg_32Bit U;                 /* Unsigned access */
    Ifx_SReg_32Bit I;                 /* Signed access */
    Ifx_QSPI_ID_Bits B;               /* Bitfield access */
} Ifx_QSPI_ID;

/* Kernel Reset Register 0   */
typedef union
{
    Ifx_UReg_32Bit U;                 /* Unsigned access */
    Ifx_SReg_32Bit I;                 /* Signed access */
    Ifx_QSPI_KRST0_Bits B;            /* Bitfield access */
} Ifx_QSPI_KRST0;

/* Kernel Reset Register 1   */
typedef union
{
    Ifx_UReg_32Bit U;                 /* Unsigned access */
    Ifx_SReg_32Bit I;                 /* Signed access */
    Ifx_QSPI_KRST1_Bits B;            /* Bitfield access */
} Ifx_QSPI_KRST1;

/* Kernel Reset Status Clear Register   */
typedef union
{
    Ifx_UReg_32Bit U;                 /* Unsigned access */
    Ifx_SReg_32Bit I;                 /* Signed access */
    Ifx_QSPI_KRSTCLR_Bits B;          /* Bitfield access */
} Ifx_QSPI_KRSTCLR;

/* Move Counter Register   */
typedef union
{
    Ifx_UReg_32Bit U;                 /* Unsigned access */
    Ifx_SReg_32Bit I;                 /* Signed access */
    Ifx_QSPI_MC_Bits B;               /* Bitfield access */
} Ifx_QSPI_MC;

/* Move Counter control Register   */
typedef union
{
    Ifx_UReg_32Bit U;                 /* Unsigned access */
    Ifx_SReg_32Bit I;                 /* Signed access */
    Ifx_QSPI_MCCON_Bits B;            /* Bitfield access */
} Ifx_QSPI_MCCON;

/* MIX_ENTRY Register   */
typedef union
{
    Ifx_UReg_32Bit U;                 /* Unsigned access */
    Ifx_SReg_32Bit I;                 /* Signed access */
    Ifx_QSPI_MIXENTRY_Bits B;         /* Bitfield access */
} Ifx_QSPI_MIXENTRY;

/* OCDS Control and Status   */
typedef union
{
    Ifx_UReg_32Bit U;                 /* Unsigned access */
    Ifx_SReg_32Bit I;                 /* Signed access */
    Ifx_QSPI_OCS_Bits B;              /* Bitfield access */
} Ifx_QSPI_OCS;

/* Port Input Select Register   */
typedef union
{
    Ifx_UReg_32Bit U;                 /* Unsigned access */
    Ifx_SReg_32Bit I;                 /* Signed access */
    Ifx_QSPI_PISEL_Bits B;            /* Bitfield access */
} Ifx_QSPI_PISEL;

/* RX_EXIT Register   */
typedef union
{
    Ifx_UReg_32Bit U;                 /* Unsigned access */
    Ifx_SReg_32Bit I;                 /* Signed access */
    Ifx_QSPI_RXEXIT_Bits B;           /* Bitfield access */
} Ifx_QSPI_RXEXIT;

/* RX_EXIT Debug Register   */
typedef union
{
    Ifx_UReg_32Bit U;                 /* Unsigned access */
    Ifx_SReg_32Bit I;                 /* Signed access */
    Ifx_QSPI_RXEXITD_Bits B;          /* Bitfield access */
} Ifx_QSPI_RXEXITD;

/* Slave Select Output Control Register   */
typedef union
{
    Ifx_UReg_32Bit U;                 /* Unsigned access */
    Ifx_SReg_32Bit I;                 /* Signed access */
    Ifx_QSPI_SSOC_Bits B;             /* Bitfield access */
} Ifx_QSPI_SSOC;

/* Status Register   */
typedef union
{
    Ifx_UReg_32Bit U;                 /* Unsigned access */
    Ifx_SReg_32Bit I;                 /* Signed access */
    Ifx_QSPI_STATUS_Bits B;           /* Bitfield access */
} Ifx_QSPI_STATUS;

/* Status Register 1   */
typedef union
{
    Ifx_UReg_32Bit U;                 /* Unsigned access */
    Ifx_SReg_32Bit I;                 /* Signed access */
    Ifx_QSPI_STATUS1_Bits B;          /* Bitfield access */
} Ifx_QSPI_STATUS1;

/* Extra Large Data Configuration Register   */
typedef union
{
    Ifx_UReg_32Bit U;                 /* Unsigned access */
    Ifx_SReg_32Bit I;                 /* Signed access */
    Ifx_QSPI_XXLCON_Bits B;           /* Bitfield access */
} Ifx_QSPI_XXLCON;


/******************************************************************************/
/* IfxSfr_Qspi_Registers_struct */
/******************************************************************************/
/** \name Object L0
 * \{  */

/* QSPI object */
typedef volatile struct _Ifx_QSPI
{
       Ifx_QSPI_CLC                        CLC;                    /* 0, Clock Control Register*/
       Ifx_QSPI_PISEL                      PISEL;                  /* 4, Port Input Select Register*/
       Ifx_QSPI_ID                         ID;                     /* 8, Module Identification Register*/
       Ifx_UReg_8Bit                       reserved_C[4];          /* C, internal Reserved */
       Ifx_QSPI_GLOBALCON                  GLOBALCON;              /* 10, Global Configuration Register*/
       Ifx_QSPI_GLOBALCON1                 GLOBALCON1;             /* 14, Global Configuration Register 1*/
       Ifx_QSPI_BACON                      BACON;                  /* 18, Basic Configuration Register*/
       Ifx_UReg_8Bit                       reserved_1C[4];         /* 1C, internal Reserved */
       Ifx_QSPI_ECON                       ECON[8];                /* 20, Configuration Extension ${z}*/
       Ifx_QSPI_STATUS                     STATUS;                 /* 40, Status Register*/
       Ifx_QSPI_STATUS1                    STATUS1;                /* 44, Status Register 1*/
       Ifx_QSPI_SSOC                       SSOC;                   /* 48, Slave Select Output Control Register*/
       Ifx_UReg_8Bit                       reserved_4C[8];         /* 4C, internal Reserved */
       Ifx_QSPI_FLAGSCLEAR                 FLAGSCLEAR;             /* 54, Flags Clear Register*/
       Ifx_QSPI_XXLCON                     XXLCON;                 /* 58, Extra Large Data Configuration Register*/
       Ifx_QSPI_MIXENTRY                   MIXENTRY;               /* 5C, MIX_ENTRY Register*/
       Ifx_QSPI_BACONENTRY                 BACONENTRY;             /* 60, BACON_ENTRY Register*/
       Ifx_QSPI_DATAENTRY                  DATAENTRY[8];           /* 64, DATA_ENTRY Register ${x}*/
       Ifx_UReg_8Bit                       reserved_84[12];        /* 84, internal Reserved */
       Ifx_QSPI_RXEXIT                     RXEXIT;                 /* 90, RX_EXIT Register*/
       Ifx_QSPI_RXEXITD                    RXEXITD;                /* 94, RX_EXIT Debug Register*/
       Ifx_UReg_8Bit                       reserved_98[12];        /* 98, internal Reserved */
       Ifx_QSPI_MC                         MC;                     /* A4, Move Counter Register*/
       Ifx_QSPI_MCCON                      MCCON;                  /* A8, Move Counter control Register*/
       Ifx_UReg_8Bit                       reserved_AC[60];        /* AC, internal Reserved */
       Ifx_QSPI_OCS                        OCS;                    /* E8, OCDS Control and Status*/
       Ifx_QSPI_KRSTCLR                    KRSTCLR;                /* EC, Kernel Reset Status Clear Register*/
       Ifx_QSPI_KRST1                      KRST1;                  /* F0, Kernel Reset Register 1*/
       Ifx_QSPI_KRST0                      KRST0;                  /* F4, Kernel Reset Register 0*/
       Ifx_QSPI_ACCEN1                     ACCEN1;                 /* F8, Access Enable Register 1*/
       Ifx_QSPI_ACCEN0                     ACCEN0;                 /* FC, Access Enable Register 0*/
} Ifx_QSPI;

/******************************************************************************/


/******************************************************************************/

/******************************************************************************/

#endif  /* IFXQSPI_REGDEF_H */
